### ISSUE TITLE
How to get this?

### ISSUE THREAD

**Issue by Sansekai** [Shubhamrawat5/whatsapp-bot#2]
![20220120_105718](https://user-images.githubusercontent.com/34540627/150264200-a070ca40-fcc8-419a-9d26-37f28c017f76.jpg)

https://github.com/Shubhamrawat5/whatsapp-bot/blob/78e9d3fa1c695bcbad7730bb1695f74d08323617/functions/insta.js#L24

Btw i use httpcanary android

**Comment by Shubhamrawat5** [comment]
From where i get.

In Chrome
Right click -> Inspect -> Network
Then open a reel url and cancel it, there in network section you would see the request data and there you would have cookie value.

**Comment by Sansekai** [comment]
> From where i get.
> 
> In Chrome Right click -> Inspect -> Network Then open a reel url and cancel it, there in network section you would see the request data and there you would have cookie value.

Thx
